export {Button} from './UI/Button/Button'
export {Input} from './UI/Input/Input'
export {Loader} from './UI/Loader/Loader'
export {Modal} from './UI/Modal/Modal'
export {figureImages} from './lib/figureImages'
export * as boardUtils from './lib/boardUtils'
export * as responses from './lib/boardUtils'
export {addFigures} from './lib/setFiguresOffline'
export {useAuth} from './lib/hooks/useAuth'
export {useGameData} from './lib/hooks/useGameData'
export {useInput} from './lib/hooks/useInput'
export {useVictory} from './lib/hooks/useVictory'

